# Site settings
title: Free as in Blog Posts
email: me@benmosher.com
description: > # this means to ignore newlines until "baseurl:"
  Ben Mosher blog, v3.0.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://benmosher.github.io" # the base hostname & protocol for your site
twitter_username: benmosher
github_username:  benmosher

# Build settings
markdown: kramdown
